[project]
name = "lfox"
version = "0.1.0"
description = 'Lattice Fields Over jaX'
readme = "README.md"
license = "MIT"
authors = [
  { name = "Ethan Neil", email = "ethan.neil@colorado.edu" },
]
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.13.7",
    "jax>=0.10.0",
    "jupyter>=1.1.1",
    "jupytext>=1.19.4",
    "lsqfit>=13.3",
    "matplotlib>=3.10.3",
    "ml-dtypes>=0.5.1",
    "numpy>=2.4.4",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
metal = [
    "jax-metal>=0.1.1",
]

[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.0",
]
